### ISSUE TITLE
6. What Matters Most?—Correlation Aboard the Titanic: Can't compare str with int

### ISSUE THREAD

**Issue by Mintri1199** [MakeSchool-Tutorials/Titanic-Dataset-Tutorial#2]
In section `WOMEN AND CHILDREN FIRST` the code example for finding the correlation between Sex and Survivability gave a type error. 

Error: `TypeError: unsupported operand type(s) for /: 'str' and 'int'`

My solution for this derived from this StackOverflow [post](https://stackoverflow.com/questions/48873233/is-there-a-way-to-get-correlation-with-string-data-and-a-numerical-value-in-pand):

`df.Sex.str.get_dummies().corrwith(df.Survived/df.Survived.max())`

Result:
```
female    0.543351
male     -0.543351
dtype: float64
```

**Comment by ibirnam** [comment]
@Mintri1199 - thanks for catching this! Fixed in 130531b16c19e013d4a179c0d8c41282839a4630, live now in the tutorial
